[workspace]
resolver = "3"
members = [
  "rust/phon",
  "rust/phon-codegen",
  "rust/phon-conformance",
  "rust/phon-engine",
  "rust/phon-ir",
  "rust/phon-jit",
  "rust/phon-schema",
]

[workspace.package]
version = "0.2.0-rc.5"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bearcove/phon"
homepage = "https://github.com/bearcove/phon"

[workspace.dependencies]
blake3 = { version = "1", default-features = false }
copypatch = "0.2.0-rc.5"
facet = "0.50.0-rc.7"
facet-json = "0.50.0-rc.7"
facet-value = "0.50.0-rc.7"
phon = { path = "rust/phon", version = "0.2.0-rc.6" }
phon-codegen = { path = "rust/phon-codegen", version = "0.2.0-rc.6" }
phon-conformance = { path = "rust/phon-conformance", version = "0.2.0-rc.6" }
phon-engine = { path = "rust/phon-engine", version = "0.2.0-rc.6" }
phon-ir = { path = "rust/phon-ir", version = "0.2.0-rc.6" }
phon-jit = { path = "rust/phon-jit", version = "0.2.0-rc.6" }
phon-schema = { path = "rust/phon-schema", version = "0.2.0-rc.6" }
taxon = "0.2.0-rc.5"
weavy = "0.2.3-rc.0"
proptest = "1"
tracing = { version = "0.1.43", default-features = false, features = ["std", "attributes"] }
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["fmt", "std", "env-filter"] }


[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(facet_no_doc)", "cfg(kani)"] }

[workspace.lints.clippy]
disallowed_methods = "deny"
